USE ORU_SOURCE_SVC;

CREATE TABLE supplier_details (
    supplier_code     					VARCHAR(6)		NOT NULL	COMMENT 'First letter should be company name first character + autogenerated 5 digit value',
    supplier_company_name   			VARCHAR(128)	NOT NULL,
    supplier_industry                   VARCHAR(32)     NOT NULL,
    company_year_of_experience  		VARCHAR(3)		NOT NULL	COMMENT 'Assuming company will have less than 999 years of experience',
    supplier_customer_reference 		VARCHAR(128)				COMMENT 'Supplier customer\'s company name',
    supplier_customer_ref_contact_id   	INT							COMMENT 'Supplier customer\'s company contact',
    supplier_rating   					DECIMAL(2, 1)				COMMENT 'Added for future. This will be updated by admin for now based on the details provided by the supplier.',
    attachment_available        		VARCHAR(1)		NOT NULL	COMMENT 'Company should always provide attachments, handle in the screen - relaxation can be allowed for some companies.',
    create_timestamp        			TIMESTAMP 		NOT NULL 	DEFAULT CURRENT_TIMESTAMP,
    update_timestamp        			TIMESTAMP 		NOT NULL 	DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE supplier_details COMMENT = 'This table holds supplier complete details.';

ALTER TABLE supplier_details
ADD CONSTRAINT xpk_supplier_details
PRIMARY KEY (supplier_code);

ALTER TABLE supplier_details
ADD CHECK (attachment_available IN ('Y', 'N'));
