USE ORU_SOURCE_SVC;

CREATE TABLE supplier_company_turn_over (
    company_turn_over_id    INT				NOT NULL  AUTO_INCREMENT PRIMARY KEY COMMENT 'autogenerated - since company can provide more than one year data, so autogenerated id is used for PK',
    supplier_code		   	VARCHAR(128)	NOT NULL,
    financial_year   		VARCHAR(9)		NOT NULL				  			 COMMENT 'should be drop down in screen. supplier should provide details atleast for 1 year.',
    turn_over_in_lakhs   	DECIMAL(12, 2)	NOT NULL				 			 COMMENT 'turn over should be in lakhs and handled in screen',
    iso_currency_code   	VARCHAR(3)		NOT NULL,
    create_timestamp        TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_timestamp        TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE supplier_company_turn_over COMMENT = 'This table holds supplier company turn over details - should be retrieved using supplier_code.';
