USE ORU_SOURCE_SVC;

CREATE TABLE purchase_order_quote_map (
	purchase_order_quote_map_id		BIGINT		NOT NULL	AUTO_INCREMENT	PRIMARY KEY COMMENT	'Auto-generated, sequence value. Internal Identifier.',
	purchase_order_number			VARCHAR(32)	NOT NULL								COMMENT	'autogenerated - financial year(2021) + 6 digits (000001) sequence',
	supplier_quote_header_id		BIGINT		NOT NULL,
	supplier_code					VARCHAR(6)	NOT NULL,
	purchase_order_owner_id     	INT			NOT NULL								COMMENT	'person who creates the purchase order',
	purchase_order_create_date		DATE		NOT NULL,
	rfq_id							BIGINT		NOT NULL,
	purchase_currency				VARCHAR(3)	NOT NULL,
	approval_type					VARCHAR(64)	NOT NULL,
	assigned_to                     INT         NOT NULL                                COMMENT 'used to identify the PO is assigned to which approver user',
    approval_flow                   VARCHAR(64) NOT NULL,
    approved_by						INT,
	purchase_order_status			VARCHAR(32)	NOT NULL,
	attachment_available			VARCHAR(1)	NOT NULL,
    create_timestamp        		TIMESTAMP 	NOT NULL 	DEFAULT CURRENT_TIMESTAMP,
    update_timestamp        		TIMESTAMP 	NOT NULL 	DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE purchase_order_quote_map COMMENT = 'Purchase order will be created against the quote offered by the supplier. This table holds the purchase order details.';

ALTER TABLE purchase_order_quote_map
ADD CONSTRAINT xunique_purchase_order_quote_map
UNIQUE KEY (purchase_order_number);

CREATE INDEX xindx_purc_order_quote_map_sup_quote_id
ON purchase_order_quote_map (supplier_quote_header_id);

CREATE INDEX xindx_purc_order_quote_map_owner_id
ON purchase_order_quote_map (purchase_order_owner_id);

CREATE INDEX xindx_purc_order_quote_map_rfq_id
ON purchase_order_quote_map (rfq_id);

ALTER TABLE purchase_order_quote_map
ADD CHECK (attachment_available IN ('Y', 'N'));
